"demo": # 此处为最外层的模块服务字段
  icon: IAM # 服务的图标
  sort: 1
  organization: # 组织层的菜单
    - "hello": # 菜单字段
        icon: manage_organization  # 菜单图标
        Routes: /demo/hello # 菜单对应路由
        sort: 1 # 菜单的次序
        permission: # 菜单内容具有的权限
          - 'demo-service.demo.hello'
  # site: # site层的菜单
  # project: # 项目层的菜单
  # user: # 个人中心层的菜单
